-- =============================================================================================
-- AUTHENTICATION TABLES
-- =============================================================================================

-- Core entities
CREATE TABLE authentication.users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_users
		PRIMARY KEY(id),
	CONSTRAINT uq_users_username
		UNIQUE(username),
	CONSTRAINT uq_users_email
		UNIQUE(email)
);

CREATE TABLE authentication.roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(255),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_roles
		PRIMARY KEY(id),
	CONSTRAINT uq_roles_name
		UNIQUE(name)
);

-- Relationships
CREATE TABLE authentication.user_roles (
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL,
	assigned_by BIGINT,
	assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_user_roles
		PRIMARY KEY(user_id, role_id),
	CONSTRAINT fk_user_roles_user
		FOREIGN KEY(user_id)
		REFERENCES authentication.users(id),
	CONSTRAINT fk_user_roles_role
		FOREIGN KEY(role_id)
		REFERENCES authentication.roles(id),
	CONSTRAINT fk_user_roles_assigned_by
		FOREIGN KEY(assigned_by)
		REFERENCES authentication.users(id)
);

-- Session management
CREATE TABLE authentication.sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	token VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMPTZ NOT NULL,
	closed_at TIMESTAMPTZ,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_sessions
		PRIMARY KEY(id),
	CONSTRAINT fk_sessions_user
		FOREIGN KEY(user_id)
		REFERENCES authentication.users(id),
	CONSTRAINT uq_sessions_token
		UNIQUE(token),
	CONSTRAINT ck_sessions_dates
		CHECK(
			expires_at > created_at
			AND (
				closed_at IS NULL
				OR closed_at > created_at
			)
		)
);

-- =============================================================================================
-- COMMERCIAL TABLES
-- =============================================================================================

-- Core entities
CREATE TABLE commerce.customers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	dni VARCHAR(15) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	address VARCHAR(150) NOT NULL,
	province VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	postal_code VARCHAR(10) NOT NULL,
	country VARCHAR(50) NOT NULL,
	delivery_window_start TIME,
	delivery_window_end TIME,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_customers
		PRIMARY KEY(id),
	CONSTRAINT ck_customers_delivery_window
		CHECK(
			(delivery_window_start IS NULL AND delivery_window_end IS NULL)
			OR
			(
				delivery_window_start IS NOT NULL
				AND delivery_window_end IS NOT NULL
				AND delivery_window_end > delivery_window_start
			)
		)
);

CREATE TABLE commerce.employees (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20),
	position VARCHAR(50) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_employees
		PRIMARY KEY(id),
	CONSTRAINT uq_employees_email
		UNIQUE(email)
);

CREATE TABLE commerce.logistics_companies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	company_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(255),
	CONSTRAINT pk_logistics_companies
		PRIMARY KEY(id),
	CONSTRAINT uq_logistics_companies_name
    	UNIQUE(company_name)
);

CREATE TABLE commerce.independent_shippers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(255),
	CONSTRAINT pk_independent_shippers
		PRIMARY KEY(id)
);

CREATE TABLE commerce.zones (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	zone_type VARCHAR(50),
	description VARCHAR(150),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_zones
		PRIMARY KEY(id),
	CONSTRAINT uq_zones_name
    	UNIQUE(name)
);

CREATE TABLE commerce.categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(500),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_categories
		PRIMARY KEY(id),
	CONSTRAINT uq_categories_name
		UNIQUE(name),
	CONSTRAINT ck_categories_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.warehouses (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	warehouse_name VARCHAR(100) NOT NULL,
	address VARCHAR(255),
	description VARCHAR(255),
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_warehouses
		PRIMARY KEY(id),
	CONSTRAINT uq_warehouses_name
		UNIQUE(warehouse_name),
	CONSTRAINT ck_warehouses_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.suppliers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	company_name VARCHAR(150) NOT NULL,
	cuit VARCHAR(20) NOT NULL,
	contact_name VARCHAR(100),
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(200),
	city VARCHAR(200),
	province VARCHAR(100),
	country VARCHAR(100),
	postal_code VARCHAR(20),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_suppliers
		PRIMARY KEY(id),
	CONSTRAINT uq_suppliers_cuit
		UNIQUE(cuit),
	CONSTRAINT ck_suppliers_dates
		CHECK(updated_at >= created_at)
);

-- Dependent entities
CREATE TABLE commerce.orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	employee_id BIGINT NOT NULL,
	customer_id BIGINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	order_status VARCHAR(20) NOT NULL,
	CONSTRAINT pk_orders
		PRIMARY KEY(id),
	CONSTRAINT fk_orders_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id), 
	CONSTRAINT fk_orders_customer_id
		FOREIGN KEY(customer_id)
		REFERENCES commerce.customers(id),
	CONSTRAINT ck_orders_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.shippers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	shipper_type VARCHAR(20) NOT NULL,
	employee_id BIGINT,
	logistic_company_id BIGINT,
	independent_shipper_id BIGINT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_shippers
		PRIMARY KEY(id),
	CONSTRAINT fk_shippers_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id),
	CONSTRAINT fk_shippers_logistic_company_id
		FOREIGN KEY(logistic_company_id)
		REFERENCES commerce.logistics_companies(id),
	CONSTRAINT fk_shippers_independent_shipper_id
		FOREIGN KEY(independent_shipper_id)
		REFERENCES commerce.independent_shippers(id),
	CONSTRAINT uq_shippers_employee_id
		UNIQUE(employee_id),
	CONSTRAINT uq_shippers_logistic_company_id
		UNIQUE(logistic_company_id), 
	CONSTRAINT uq_shippers_independent_shipper_id
		UNIQUE(independent_shipper_id),
	CONSTRAINT ck_shippers_shipper_type
		CHECK(
			(shipper_type = 'employee'
			AND employee_id IS NOT NULL
			AND logistic_company_id IS NULL
			AND independent_shipper_id IS NULL)
			OR
			(shipper_type = 'company'
			AND employee_id IS NULL
			AND logistic_company_id IS NOT NULL
			AND independent_shipper_id IS NULL)
			OR
			(shipper_type = 'independent'
			AND employee_id IS NULL
			AND logistic_company_id IS NULL
			AND independent_shipper_id IS NOT NULL)
		)
);

CREATE TABLE commerce.deliveries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	shipper_id BIGINT NOT NULL,
	scheduled_delivery_date DATE NOT NULL,
	departure_datetime TIMESTAMPTZ NOT NULL,
	estimated_arrival_datetime TIMESTAMPTZ NOT NULL,
	delivery_address VARCHAR(150) NOT NULL,
	delivery_status VARCHAR(30) NOT NULL,
	CONSTRAINT pk_deliveries
		PRIMARY KEY(id),
	CONSTRAINT fk_deliveries_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT fk_deliveries_shipper_id
		FOREIGN KEY(shipper_id)
		REFERENCES commerce.shippers(id),
	CONSTRAINT ck_deliveries_datetime
    CHECK (estimated_arrival_datetime >= departure_datetime)
);

CREATE TABLE commerce.shipper_zone_assignments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	shipper_id BIGINT NOT NULL,
	zone_id BIGINT NOT NULL,
	weekday VARCHAR(15),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_shipper_zone_assignments
		PRIMARY KEY(id),
	CONSTRAINT fk_shipper_zone_assignments_shipper_id
		FOREIGN KEY(shipper_id)
		REFERENCES commerce.shippers(id),
	CONSTRAINT fk_shipper_zone_assignments_zone_id
		FOREIGN KEY(zone_id)
		REFERENCES commerce.zones(id),
	CONSTRAINT ck_shipper_zone_assignments
		CHECK(
			weekday IS NULL
			OR weekday IN (
				'monday',
				'tuesday',
				'wednesday',
				'thursday',
				'friday',
				'saturday',
				'sunday'
			)
		),
	CONSTRAINT ck_shipper_zone_assignments_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	category_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	barcode VARCHAR(50),
	name VARCHAR(150) NOT NULL,
	description VARCHAR(500),
	unit_of_measure VARCHAR(20) NOT NULL,
	sale_price DECIMAL(10,2) NOT NULL,
	minimum_stock INT NOT NULL,
	maximum_stock INT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_products
		PRIMARY KEY(id),
	CONSTRAINT fk_products_category_id
		FOREIGN KEY(category_id)
		REFERENCES commerce.categories(id),
	CONSTRAINT uq_products_product_code
		UNIQUE(product_code),
	CONSTRAINT uq_products_barcode
		UNIQUE(barcode),
	CONSTRAINT ck_products_min_max_stock
		CHECK(
			minimum_stock >= 0
			AND (
				maximum_stock IS NULL
				OR maximum_stock >= minimum_stock
			)
		),
	CONSTRAINT ck_products_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.order_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_price DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(10,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	line_total DECIMAL(10,2) NOT NULL,
	CONSTRAINT pk_order_details
		PRIMARY KEY(id),
	CONSTRAINT fk_order_details_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT fk_order_details_product_id
		FOREIGN KEY(product_id)
		REFERENCES commerce.products(id),
	CONSTRAINT ck_order_details_discount_rate
		CHECK(discount_rate >= 0 AND discount_rate <= 100),
	CONSTRAINT ck_order_details_discount_amount
		CHECK(discount_amount >= 0),
	CONSTRAINT ck_order_details_tax_rate
		CHECK(tax_rate >= 0 AND tax_rate <= 100),
	CONSTRAINT ck_order_details_quantity
   	 	CHECK(quantity > 0),
	CONSTRAINT ck_order_details_unit_price
    	CHECK(unit_price >= 0),
	CONSTRAINT ck_order_details_line_total
    	CHECK(line_total >= 0)
);

CREATE TABLE commerce.invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	invoice_number VARCHAR(30) NOT NULL,
	invoice_type VARCHAR(5) NOT NULL,
	issue_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	due_date DATE,
	subtotal DECIMAL(10,2) NOT NULL,
	discount_total DECIMAL(10,2) NOT NULL,
	tax_total DECIMAL(10,2) NOT NULL,
	total DECIMAL(10,2) NOT NULL,
	status VARCHAR(20) NOT NULL,
	notes VARCHAR(500),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_invoices
		PRIMARY KEY(id),
	CONSTRAINT fk_invoices_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT uq_invoices_invoice_number
		UNIQUE(invoice_number),
	CONSTRAINT ck_invoices_amounts
		CHECK(
			subtotal >= 0
			AND discount_total >= 0
			AND tax_total >= 0
			AND total >= 0
		),
	CONSTRAINT ck_invoices_due_date
		CHECK(due_date IS NULL OR due_date >= CAST(issue_date AS DATE)),
	CONSTRAINT ck_invoices_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.invoice_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	invoice_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_price DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(10,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	tax_amount DECIMAL(10,2) NOT NULL,
	line_total DECIMAL(10,2) NOT NULL,
	CONSTRAINT pk_invoices_details
		PRIMARY KEY(id),
	CONSTRAINT fk_invoice_details_invoice_id
		FOREIGN KEY(invoice_id)
		REFERENCES commerce.invoices(id),
	CONSTRAINT fk_invoice_details_product_id
		FOREIGN KEY(product_id)
		REFERENCES commerce.products(id),
	CONSTRAINT ck_invoice_details_amounts
		CHECK(
			unit_price > 0
			AND quantity > 0
			AND discount_rate >= 0 AND discount_rate <= 100
			AND discount_amount >= 0
			AND tax_rate >= 0 AND tax_rate <= 100
			AND tax_amount >= 0
			AND line_total >= 0
		)
);

CREATE TABLE commerce.supplier_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	supplier_id BIGINT NOT NULL,
	document_name VARCHAR(150) NOT NULL,
	document_type VARCHAR(50) NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	version VARCHAR(20),
	uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_current BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_supplier_documents
		PRIMARY KEY(id),
	CONSTRAINT fk_supplier_documents_supplier_id
		FOREIGN KEY(supplier_id)
		REFERENCES commerce.suppliers(id),
	CONSTRAINT ck_supplier_documents_file_path
    	CHECK (LENGTH(TRIM(file_path)) > 0)
);

CREATE TABLE commerce.supplier_products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	supplier_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	supplier_product_code VARCHAR(50),
	purchase_cost DECIMAL(10,2) NOT NULL,
	minimum_order_quantity INT,
	lead_time_days INT,
	is_preferred_supplier BOOLEAN NOT NULL DEFAULT FALSE,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_supplier_products
		PRIMARY KEY(id),
	CONSTRAINT fk_supplier_products_supplier_id
		FOREIGN KEY(supplier_id)
		REFERENCES commerce.suppliers(id),
	CONSTRAINT fk_supplier_products_product_id
		FOREIGN KEY(product_id)
		REFERENCES commerce.products(id),
	CONSTRAINT uq_supplier_products_supplier_product
		UNIQUE(supplier_id, product_id),
	CONSTRAINT ck_supplier_products_purchase_cost
		CHECK(purchase_cost > 0),
	CONSTRAINT ck_supplier_products_min_order_quantity
		CHECK(minimum_order_quantity IS NULL OR minimum_order_quantity > 0),
	CONSTRAINT ck_supplier_products_days
		CHECK(lead_time_days IS NULL OR lead_time_days >= 0),
	CONSTRAINT ck_supplier_products_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.purchase_orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	employee_id BIGINT NOT NULL,
	supplier_id BIGINT NOT NULL,
	order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expected_delivery_date DATE,
	status VARCHAR(30) NOT NULL,
	notes VARCHAR(500),
	total_amount DECIMAL(12,2) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_purchase_orders
		PRIMARY KEY(id),
	CONSTRAINT fk_purchase_orders_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id),
	CONSTRAINT fk_purchase_orders_supplier_id
		FOREIGN KEY(supplier_id)
		REFERENCES commerce.suppliers(id),
	CONSTRAINT ck_purchase_orders_order_expected_delivery
		CHECK(expected_delivery_date >= CAST(order_date AS DATE)),
	CONSTRAINT ck_purchase_orders_total_amount
		CHECK(total_amount >= 0),
	CONSTRAINT ck_purchase_orders_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.purchase_order_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	purchase_order_id BIGINT NOT NULL,
	supplier_product_id BIGINT NOT NULL,
	supplier_product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_cost DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(10,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	line_total DECIMAL(12,2) NOT NULL,
	CONSTRAINT pk_purchase_order_details
		PRIMARY KEY(id),
	CONSTRAINT fk_purchase_order_details_purchase_order_id
		FOREIGN KEY(purchase_order_id)
		REFERENCES commerce.purchase_orders(id),
	CONSTRAINT fk_purchase_order_details_supplier_product_id
		FOREIGN KEY(supplier_product_id)
		REFERENCES commerce.supplier_products(id),
	CONSTRAINT ck_purchase_order_details_quantity
		CHECK(quantity > 0),
	CONSTRAINT ck_purchase_order_details_unit_cost
		CHECK(unit_cost > 0),
	CONSTRAINT ck_purchase_order_details_discount_rate
		CHECK(discount_rate >= 0 AND discount_rate <= 100),
	CONSTRAINT ck_purchase_order_details_discount_amount
		CHECK(discount_amount >= 0),
	CONSTRAINT ck_purchase_order_details_tax_rate
		CHECK(tax_rate >= 0 AND tax_rate <= 100),
	CONSTRAINT ck_purchase_order_details_line_total
		CHECK(line_total >= 0)
);

CREATE TABLE commerce.purchase_receipts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	employee_id BIGINT NOT NULL,
	purchase_order_id BIGINT NOT NULL,
	received_number VARCHAR(30) NOT NULL,
	received_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(30) NOT NULL,
	notes VARCHAR(500),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_purchase_receipts
		PRIMARY KEY(id),
	CONSTRAINT fk_purchase_receipts_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id),
	CONSTRAINT fk_purchase_receipts_purchase_order_id
		FOREIGN KEY(purchase_order_id)
		REFERENCES commerce.purchase_orders(id),
	CONSTRAINT ck_purchase_receipts_dates
		CHECK(
			created_at >= received_date
			AND updated_at >= created_at
		)
);

CREATE TABLE commerce.purchase_receipt_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	purchase_receipt_id BIGINT NOT NULL,
	supplier_product_id BIGINT NOT NULL,
	supplier_product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity_received DECIMAL(10,2) NOT NULL,
	unit_cost DECIMAL(10,2) NOT NULL,
	notes VARCHAR(500),
	CONSTRAINT pk_purchase_receipt_details
		PRIMARY KEY(id),
	CONSTRAINT fk_purchase_receipt_details_purchase_receipt_id
		FOREIGN KEY(purchase_receipt_id)
		REFERENCES commerce.purchase_receipts(id),
	CONSTRAINT fk_purchase_receipt_details_supplier_product_id
		FOREIGN KEY(supplier_product_id)
		REFERENCES commerce.supplier_products(id),
	CONSTRAINT ck_purchase_receipt_details_quantity
		CHECK(quantity_received > 0),
	CONSTRAINT ck_purchase_receipt_details_unit_cost
    CHECK (unit_cost > 0)
);

CREATE TABLE commerce.supplier_invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	supplier_id BIGINT NOT NULL,
	invoice_number VARCHAR(50) NOT NULL,
	invoice_type VARCHAR(5) NOT NULL,
	issue_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	due_date DATE,
	subtotal DECIMAL(12,2) NOT NULL,
	discount_total DECIMAL(10,2) NOT NULL,
	tax_total DECIMAL(12,2) NOT NULL,
	total DECIMAL(12,2) NOT NULL,
	status VARCHAR(50) NOT NULL,
	notes VARCHAR(500),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_supplier_invoices
		PRIMARY KEY(id),
	CONSTRAINT fk_supplier_invoices_supplier_id
		FOREIGN KEY(supplier_id)
		REFERENCES commerce.suppliers(id),
	CONSTRAINT uq_supplier_invoices_supplier_invoice
		UNIQUE(supplier_id, invoice_number)
	CONSTRAINT ck_supplier_invoices_due_date
		CHECK(due_date IS NULL OR due_date >= CAST(issue_date AS DATE)),
	CONSTRAINT ck_supplier_invoices_total_data
		CHECK(
			subtotal > 0
			AND discount_total >= 0
			AND tax_total >= 0
			AND total > 0
		),
	CONSTRAINT ck_supplier_invoices_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.supplier_invoice_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	supplier_invoice_id BIGINT NOT NULL,
	supplier_product_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_cost DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(12,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	tax_amount DECIMAL(12,2) NOT NULL,
	line_total DECIMAL(12,2) NOT NULL,
	CONSTRAINT pk_supplier_invoice_details
		PRIMARY KEY(id),
	CONSTRAINT fk_supplier_invoice_details_supplier_invoice_id
		FOREIGN KEY(supplier_invoice_id)
		REFERENCES commerce.supplier_invoices(id),
	CONSTRAINT fk_supplier_invoice_details_supplier_product_id
		FOREIGN KEY(supplier_product_id)
		REFERENCES commerce.supplier_products(id),
	CONSTRAINT ck_supplier_invoice_details_amounts
		CHECK(
			unit_cost > 0
			AND quantity > 0
			AND discount_rate >= 0 AND discount_rate <= 100
			AND discount_amount >= 0
			AND tax_rate >= 0 AND tax_rate <= 100
			AND tax_amount >= 0
			AND line_total >= 0
		)
);

CREATE TABLE commerce.product_batches (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	purchase_receipt_detail_id BIGINT NOT NULL,
	batch_number VARCHAR(100) NOT NULL,
	manufacture_date DATE,
	expiration_date DATE,
	received_date DATE NOT NULL,
	initial_quantity DECIMAL(12,2) NOT NULL,
	unit_cost DECIMAL(12,2) NOT NULL,
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_product_batches
		PRIMARY KEY(id),
	CONSTRAINT fk_product_batches_purchase_receipt_detail_id
		FOREIGN KEY(purchase_receipt_detail_id)
		REFERENCES commerce.purchase_receipt_details(id),
	CONSTRAINT ck_product_batches_manufacture_date
		CHECK(
			manufacture_date IS NULL 
			OR manufacture_date <= received_date
		),
	CONSTRAINT ck_product_batches_expiration_date
		CHECK(
			expiration_date IS NULL 
			OR expiration_date > received_date 
			OR expiration_date > manufacture_date 
		),
	CONSTRAINT ck_product_batches_quantity_and_cost
		CHECK(
			initial_quantity > 0
			AND unit_cost > 0
		),
	CONSTRAINT ck_product_batches_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.stocks (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	warehouse_id BIGINT NOT NULL,
	product_batch_id BIGINT NOT NULL,
	current_quantity DECIMAL(12,2) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_stocks
		PRIMARY KEY(id),
	CONSTRAINT fk_stocks_warehouse_id
		FOREIGN KEY(warehouse_id)
		REFERENCES commerce.warehouses(id),
	CONSTRAINT fk_stocks_product_batch_id
		FOREIGN KEY(product_batch_id)
		REFERENCES commerce.product_batches(id),
	CONSTRAINT uq_stocks_warehouse_product_batch
		UNIQUE(warehouse_id, product_batch_id),
	CONSTRAINT ck_stocks_current_quantity
		CHECK(current_quantity >= 0),
	CONSTRAINT ck_stocks_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.stock_movements (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	stock_id BIGINT NOT NULL,
	movement_type VARCHAR(30) NOT NULL,
	quantity DECIMAL(12,2) NOT NULL,
	movement_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	notes VARCHAR(255),
	CONSTRAINT pk_stock_movements
		PRIMARY KEY(id),
	CONSTRAINT fk_stock_movements_stock_id
		FOREIGN KEY(stock_id)
		REFERENCES commerce.stocks(id),
	CONSTRAINT ck_stock_movements_quantity
		CHECK(quantity > 0)
);

-- Relationships
CREATE TABLE commerce.supplier_invoice_receipts (
	supplier_invoice_id BIGINT NOT  NULL,
	purchase_receipt_id BIGINT NOT NULL,
	CONSTRAINT pk_supplier_invoice_receipts
		PRIMARY KEY(supplier_invoice_id, purchase_receipt_id),
	CONSTRAINT fk_supplier_invoice_receipts_supplier_invoice_id
		FOREIGN KEY(supplier_invoice_id)
		REFERENCES commerce.supplier_invoices(id),
	CONSTRAINT fk_supplier_invoice_receipts_purchase_receipt_id
		FOREIGN KEY(purchase_receipt_id)
		REFERENCES commerce.purchase_receipts(id)
);
