-- =============================================================================================
-- AUTHENTICATION TABLES
-- =============================================================================================

-- Core entities
CREATE TABLE authentication.users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_users
		PRIMARY KEY(id),
	CONSTRAINT uq_users_username
		UNIQUE(username),
	CONSTRAINT uq_users_email
		UNIQUE(email)
);

CREATE TABLE authentication.roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(255),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_roles
		PRIMARY KEY(id),
	CONSTRAINT uq_roles_name
		UNIQUE(name)
);

-- Relationships
CREATE TABLE authentication.user_roles (
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL,
	assigned_by BIGINT,
	assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_user_roles
		PRIMARY KEY(user_id, role_id),
	CONSTRAINT fk_user_roles_user
		FOREIGN KEY(user_id)
		REFERENCES authentication.users(id),
	CONSTRAINT fk_user_roles_role
		FOREIGN KEY(role_id)
		REFERENCES authentication.roles(id),
	CONSTRAINT fk_user_roles_assigned_by
		FOREIGN KEY(assigned_by)
		REFERENCES authentication.users(id)
);

-- Session management
CREATE TABLE authentication.sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	token VARCHAR(255) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMPTZ NOT NULL,
	closed_at TIMESTAMPTZ,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_sessions
		PRIMARY KEY(id),
	CONSTRAINT fk_sessions_user
		FOREIGN KEY(user_id)
		REFERENCES authentication.users(id),
	CONSTRAINT uq_sessions_token
		UNIQUE(token),
	CONSTRAINT ck_sessions_dates
		CHECK(expires_at > created_at)
);

-- =============================================================================================
-- COMMERCIAL TABLES
-- =============================================================================================

-- Core entities
CREATE TABLE commerce.customers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	dni VARCHAR(15) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	address VARCHAR(150) NOT NULL,
	province VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	postal_code VARCHAR(10) NOT NULL,
	country VARCHAR(50) NOT NULL,
	delivery_window_start TIME,
	delivery_window_end TIME,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_customers
		PRIMARY KEY(id),
	CONSTRAINT ck_customers_delivery_window
		CHECK(delivery_window_end > delivery_window_start)
);

CREATE TABLE commerce.employees (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20),
	position VARCHAR(50) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_employees
		PRIMARY KEY(id),
	CONSTRAINT uq_employees_email
		UNIQUE(email)
);

CREATE TABLE commerce.logistics_companies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	company_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(255),
	CONSTRAINT pk_logistics_companies
		PRIMARY KEY(id)
);

CREATE TABLE commerce.independent_shippers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(255),
	CONSTRAINT pk_independent_shippers
		PRIMARY KEY(id)
);

CREATE TABLE commerce.zones (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	zone_type VARCHAR(50),
	description VARCHAR(150),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_zones
		PRIMARY KEY(id)
);

CREATE TABLE commerce.categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(500),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_categories
		PRIMARY KEY(id),
	CONSTRAINT uq_categories_name
		UNIQUE(name),
	CONSTRAINT ck_categories_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.warehouses (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	warehouse_name VARCHAR(100) NOT NULL,
	address VARCHAR(255),
	description VARCHAR(255),
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_warehouses
		PRIMARY KEY(id),
	CONSTRAINT uq_warehouses_name
		UNIQUE(warehouse_name),
	CONSTRAINT ck_warehouses_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.suppliers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	company_name VARCHAR(150) NOT NULL,
	cuit VARCHAR(20) NOT NULL,
	contact_name VARCHAR(100),
	email VARCHAR(150) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(200),
	city VARCHAR(200),
	province VARCHAR(100),
	country VARCHAR(100),
	postal_code VARCHAR(20),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_suppliers
		PRIMARY KEY(id),
	CONSTRAINT uq_suppliers_cuit
		UNIQUE(cuit),
	CONSTRAINT ck_suppliers_dates
		CHECK(updated_at >= created_at)
);

-- Dependent entities
CREATE TABLE commerce.orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	employee_id BIGINT NOT NULL,
	customer_id BIGINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	order_status VARCHAR(20) NOT NULL,
	CONSTRAINT pk_orders
		PRIMARY KEY(id),
	CONSTRAINT fk_orders_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id), 
	CONSTRAINT fk_orders_customer_id
		FOREIGN KEY(customer_id)
		REFERENCES commerce.customers(id),
	CONSTRAINT ck_orders_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.shippers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	shipper_type VARCHAR(20) NOT NULL,
	employee_id BIGINT,
	logistic_company_id BIGINT,
	independent_shipper_id BIGINT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_shippers
		PRIMARY KEY(id),
	CONSTRAINT fk_shippers_employee_id
		FOREIGN KEY(employee_id)
		REFERENCES commerce.employees(id),
	CONSTRAINT fk_shippers_logistic_company_id
		FOREIGN KEY(logistic_company_id)
		REFERENCES commerce.logistics_companies(id),
	CONSTRAINT fk_shippers_independent_shipper_id
		FOREIGN KEY(independent_shipper_id)
		REFERENCES commerce.independent_shippers(id),
	CONSTRAINT uq_shippers_employee_id
		UNIQUE(employee_id),
	CONSTRAINT uq_shippers_logistic_company_id
		UNIQUE(logistic_company_id), 
	CONSTRAINT uq_shippers_independent_shipper_id
		UNIQUE(independent_shipper_id),
	CONSTRAINT ck_shippers_shipper_type
		CHECK(
			(shipper_type = 'employee'
			AND employee_id IS NOT NULL
			AND logistic_company_id IS NULL
			AND independent_shipper_id IS NULL)
			OR
			(shipper_type = 'company'
			AND employee_id IS NULL
			AND logistic_company_id IS NOT NULL
			AND independent_shipper_id IS NULL)
			OR
			(shipper_type = 'independent'
			AND employee_id IS NULL
			AND logistic_company_id IS NULL
			AND independent_shipper_id IS NOT NULL)
		)
);

CREATE TABLE commerce.deliveries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	shipper_id BIGINT NOT NULL,
	scheduled_delivery_date DATE NOT NULL,
	departure_datetime TIMESTAMPTZ NOT NULL,
	estimated_arrival_time TIME NOT NULL,
	delivery_address VARCHAR(150) NOT NULL,
	delivery_status VARCHAR(30) NOT NULL,
	CONSTRAINT pk_deliveries
		PRIMARY KEY(id),
	CONSTRAINT fk_deliveries_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT fk_deliveries_shipper_id
		FOREIGN KEY(shipper_id)
		REFERENCES commerce.shippers(id)
);

CREATE TABLE commerce.shipper_zone_assignments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	shipper_id BIGINT NOT NULL,
	zone_id BIGINT NOT NULL,
	weekday VARCHAR(15),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_shipper_zone_assignments
		PRIMARY KEY(id),
	CONSTRAINT fk_shipper_zone_assignments_shipper_id
		FOREIGN KEY(shipper_id)
		REFERENCES commerce.shippers(id),
	CONSTRAINT fk_shipper_zone_assignments_zone_id
		FOREIGN KEY(zone_id)
		REFERENCES commerce.zones(id),
	CONSTRAINT ck_shipper_zone_assignments_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	category_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	barcode VARCHAR(50),
	name VARCHAR(150) NOT NULL,
	description VARCHAR(500),
	unit_of_measure VARCHAR(20) NOT NULL,
	sale_price DECIMAL(10,2) NOT NULL,
	minimum_stock INT NOT NULL,
	maximum_stock INT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_products
		PRIMARY KEY(id),
	CONSTRAINT fk_products_category_id
		FOREIGN KEY(category_id)
		REFERENCES commerce.categories(id),
	CONSTRAINT uq_products_product_code
		UNIQUE(product_code),
	CONSTRAINT uq_products_barcode
		UNIQUE(barcode),
	CONSTRAINT ck_products_min_max_stock
		CHECK(maximum_stock IS NULL OR maximum_stock >= minimum_stock),
	CONSTRAINT ck_products_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.order_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(150) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_price DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(10,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	line_total DECIMAL(10,2) NOT NULL,
	CONSTRAINT pk_order_details
		PRIMARY KEY(id),
	CONSTRAINT fk_order_details_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT fk_order_details_product_id
		FOREIGN KEY(product_id)
		REFERENCES commerce.products(id),
	CONSTRAINT ck_order_details_discount_rate
		CHECK(discount_rate >= 0 AND discount_rate <= 100),
	CONSTRAINT ck_order_details_discount_amount
		CHECK(discount_amount >= 0),
	CONSTRAINT ck_order_details_tax_rate
		CHECK(tax_rate >= 0 AND tax_rate <= 100),
	CONSTRAINT ck_order_details_quantity
   	 	CHECK(quantity > 0),
	CONSTRAINT ck_order_details_unit_price
    	CHECK(unit_price >= 0),
	CONSTRAINT ck_order_details_line_total
    	CHECK(line_total >= 0)
);

CREATE TABLE commerce.invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT NOT NULL,
	invoice_number VARCHAR(30) NOT NULL,
	invoice_type VARCHAR(5) NOT NULL,
	issue_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	due_date DATE,
	subtotal DECIMAL(10,2) NOT NULL,
	discount_total DECIMAL(10,2) NOT NULL,
	tax_total DECIMAL(10,2) NOT NULL,
	total DECIMAL(10,2) NOT NULL,
	status VARCHAR(20) NOT NULL,
	notes VARCHAR(500),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_invoices
		PRIMARY KEY(id),
	CONSTRAINT fk_invoices_order_id
		FOREIGN KEY(order_id)
		REFERENCES commerce.orders(id),
	CONSTRAINT uq_invoices_invoice_number
		UNIQUE(invoice_number),
	CONSTRAINT ck_invoices_amounts
		CHECK(
			subtotal >= 0
			AND discount_total >= 0
			AND tax_total >= 0
			AND total >= 0
		),
	CONSTRAINT ck_invoices_due_date
		CHECK(due_date IS NULL OR due_date >= issue_date::DATE),
	CONSTRAINT ck_invoices_dates
		CHECK(updated_at >= created_at)
);

CREATE TABLE commerce.invoice_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	invoice_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	product_code VARCHAR(50) NOT NULL,
	product_name VARCHAR(50) NOT NULL,
	unit_of_measure VARCHAR(20) NOT NULL,
	quantity DECIMAL(10,2) NOT NULL,
	unit_price DECIMAL(10,2) NOT NULL,
	discount_rate DECIMAL(5,2) NOT NULL,
	discount_amount DECIMAL(10,2) NOT NULL,
	tax_rate DECIMAL(5,2) NOT NULL,
	tax_amount DECIMAL(10,2) NOT NULL,
	line_total DECIMAL(10,2) NOT NULL,
	CONSTRAINT pk_invoices_details
		PRIMARY KEY(id),
	CONSTRAINT fk_invoice_details_invoice_id
		FOREIGN KEY(invoice_id)
		REFERENCES commerce.invoices(id),
	CONSTRAINT fk_invoice_details_product_id
		FOREIGN KEY(product_id)
		REFERENCES commerce.products(id),
	CONSTRAINT ck_invoice_details_amounts
		CHECK(
			quantity > 0
			AND discount_rate >= 0 AND discount_rate <= 100
			AND discount_amount >= 0
			AND tax_rate >= 0 AND tax_rate <= 100
			AND tax_amount >= 0
			AND line_total >= 0
		)
);

CREATE TABLE commerce.supplier_documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	supplier_id BIGINT NOT NULL,
	document_name VARCHAR(150) NOT NULL,
	document_type VARCHAR(50) NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	version VARCHAR(20),
	uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_current BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT pk_supplier_documents
		PRIMARY KEY(id),
	CONSTRAINT fk_supplier_documents_supplier_id
		FOREIGN KEY(supplier_id)
		REFERENCES commerce.suppliers(id),
	CONSTRAINT ck_supplier_documents_file_path
    	CHECK (LENGTH(TRIM(file_path)) > 0)
);

CREATE TABLE commerce.supplier_products (

);

CREATE TABLE commerce.purchase_orders (

);

CREATE TABLE commerce.purchase_order_details (

);

CREATE TABLE commerce.purchase_receipts (

);

CREATE TABLE commerce.purchase_receipt_details (

);

CREATE TABLE commerce.supplier_invoices (

);

CREATE TABLE commerce.supplier_invoice_details (

);

CREATE TABLE commerce.product_batches (

);

CREATE TABLE commerce.stocks (

);

CREATE TABLE commerce.stock_movements (

);

